### ISSUE TITLE
Docker起動時の0.0.0.0の意味を調べる

### ISSUE THREAD

**Issue by somurie06** [somurieengieer/TaxSimulater#1]

**Comment by nck06** [comment]
[コチラ](https://www.wdic.org/w/WDIC/0.0.0.0)より

0.0.0.0/0(宛先0.0.0.0、ネットマスク0.0.0.0)の場合は全てのアドレスとマッチする。
全てのホスト、任意の宛先を意味する。すなわち、デフォルトルートである。
